version: "3.7"

services:
  postgrestaxi:
    image: 'postgres:15.1'
    container_name: postgrestaxi
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - local_pgdata:/var/lib/postgresql/data
    networks:
      - taxi_aggregator

  mongo_db:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - taxi_aggregator

  ride-service:
    image: ride-service:0.0.1
    container_name: ride-service
    ports:
      - "9003:9003"
    networks:
      - taxi_aggregator
    environment:
      - SPRING_DATA_MONGODB_URL=mongodb://root:example@mongo_db:27017/
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=${DB_MONGO_PASSWORD}
      - SPRING_DATA_MONGODB_HOST=mongo_db

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - mongo_db
      - kafka

  payment-service:
    image: payment-service:0.0.1
    container_name: payment-service
    ports:
      - "9004:9004"
    networks:
      - taxi_aggregator
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgrestaxi:5432/payment
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - postgrestaxi

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
    networks:
      - taxi_aggregator

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: "no"
    networks:
      - taxi_aggregator
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    networks:
      - taxi_aggregator
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  eureka-server:
    image: eureka-server:0.0.1
    container_name: eureka-server
    networks:
      - taxi_aggregator
    ports:
      - '8761:8761'

  api-gateway:
    image: api-gateway:0.0.1
    container_name: api-gateway
    networks:
      - taxi_aggregator
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - '8765:8765'

  passenger-service:
    image: passenger-service:0.0.1
    container_name: passenger-service
    networks:
      - taxi_aggregator
    ports:
        - "9001:9001"
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgrestaxi:5432/passenger
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - postgrestaxi
      - eureka-server

  driver-service:
    image: driver-service:0.0.1
    container_name: driver-service
    ports:
      - "9002:9002"
    networks:
      - taxi_aggregator
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgrestaxi:5432/driver
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - postgrestaxi
      - kafka




volumes:
  data: {}


networks:
  taxi_aggregator:
    driver: bridge
