server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: passenger-service
          uri: lb://PASSENGER-SERVICE
          predicates:
            - Path=/api/v1/passengers/**

        - id: driver-service
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/api/v1/drivers/**
            - Path=/api/v1/cars/**

        - id: ride-service
          uri: lb://RIDE-SERVICE
          predicates:
            - Path=/api/v1/rides/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/accounts/**
            - Path=/api/v1/creditcards/**
            - Path=/api/v1/transactions/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true