server:
  port: 9004
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/payment
    username: postgres
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
feign:
  client:
    config:
      driver:
        name: driver
        url: http://localhost:9002
        path: /api/v1/drivers
      passenger:
        name: passenger
        url: http://localhost:9001
        path: /api/v1/passengers
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true