server:
  port: 9004
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/payment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
