server:
  port: 9002
spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:postgresql://localhost:5433/driver
    username: postgres
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
  kafka:
    consumer:
      group-id:
        ride: ride-creation-group
        status: edit-status-group
topic:
  name:
    ride: create.ride
    driver: available.driver
    status: change.driver.status
kafka:
  bootstrap-servers: localhost:9092
  partitions:
    count: 1
  replicas:
    count: 1
feign:
  client:
    config:
      passenger:
        name: passenger-service
        path: /api/v1/passengers
      ride:
        name: ride-service
        path: /api/v1/rides
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
management:
  health:
    circuit-breakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      passenger:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 10
        failure-rate-threshold: 50
      ride:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 10
        failure-rate-threshold: 50
