server:
  port: 9003
spring:
  application:
    name: ride-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/taxi-aggregator-realm/protocol/openid-connect/certs
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: ${DB_PASSWORD:example}
      database: ridedb
      port: 27017
      host: localhost
      auto-index-creation: true
  kafka:
    consumer:
      group-id:
        driver: driver-creation-group
topic:
  name:
    ride: create.ride
    driver: available.driver
    status: change.driver.status
kafka:
  bootstrap-servers: localhost:9092
  partitions:
    count: 1
  replicas:
    count: 1
jwt:
  auth:
    converter:
      resource-id: taxi-aggregator-client
      principal-attribute: sub
mongock:
  migration-scan-package: by.sergo.rideservice.config
feign:
  client:
    config:
      driver:
        name: driver-service
        path: /api/v1/drivers
      passenger:
        name: passenger-service
        path: /api/v1/passengers
      payment:
        name: payment-service
        path: /api/v1/creditcards
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health"]
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    circuit-breakers:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      driver:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 10
        failure-rate-threshold: 50
      passenger:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 10
        failure-rate-threshold: 50
      payment:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 10
        failure-rate-threshold: 50