spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: ridedb
      port: 27017
      host: localhost
      auto-index-creation: true
mongock:
  migration-scan-package: by.sergo.rideservice.config
server:
  port: 9003