server:
  port: 9001
spring:
  application:
    name: passenger-service
  datasource:
    url: jdbc:postgresql://localhost:5433/passenger
    username: postgres
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
feign:
  client:
    config:
      driver:
        name: driver
        url: http://localhost:9002
        path: /api/v1/drivers
      ride:
        name: ride
        url: http://localhost:9003
        path: /api/v1/rides
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
