server:
  port: 9001
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/passenger
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db.changelog/db.changelog-master.yaml
  jpa:
    show-sql: true