server:
  port: 9001
spring:
  application:
    name: passenger-service
  cloud:
    discovery:
      client:
        simple:
          instances:
            api-gateway[0]:
              uri: http://localhost:8765
  datasource:
    url: jdbc:postgresql://localhost:5433/passenger
    username: postgres
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
feign:
  client:
    config:
      driver:
        name: driver-service
        path: /api/v1/drivers
      ride:
        name: ride-service
        path: /api/v1/rides
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health"]
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    circuit-breakers:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      driver:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 10
        failure-rate-threshold: 50
      ride:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 10
        failure-rate-threshold: 50